const PROVIDER_SEARCH_CIRCLE_MAX_RADIUS = 200;
const PROVIDER_SEARCH_CIRCLE_RESET_RADIUS = 50;
const PROVIDER_SEARCH_CIRCLE_INCREMENT = 2;

function getNextProviderSearchRadius(currentRadius) {
  const nextRadius = currentRadius + PROVIDER_SEARCH_CIRCLE_INCREMENT;
  return nextRadius > PROVIDER_SEARCH_CIRCLE_MAX_RADIUS ? PROVIDER_SEARCH_CIRCLE_RESET_RADIUS : nextRadius;
}

module.exports = {
  PROVIDER_SEARCH_CIRCLE_MAX_RADIUS,
  PROVIDER_SEARCH_CIRCLE_RESET_RADIUS,
  PROVIDER_SEARCH_CIRCLE_INCREMENT,
  getNextProviderSearchRadius,
};
